// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Lottery","status":true,"description":"","parameters":{}},
{"name":"DayAndNight","status":true,"description":"","parameters":{}}
];
